version: 2

defaults: &defaults
  working_directory: ~/ng
  docker:
    - image: angular/ngcontainer

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install
      - run: npm run test

  integration:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-simple{{ .Branch }}-{{ checksum "tests/@angular-devkit/build-optimizer/webpack/simple-app" }}
      - restore_cache:
          key: angular_devkit-integration-aio{{ .Branch }}-{{ checksum "tests/@angular-devkit/build-optimizer/webpack/aio-app" }}

      - run: npm install
      - run: xvfb-run -a npm run integration

      - save_cache:
          key: angular_devkit-integration-simple{{ .Branch }}-{{ checksum "tests/@angular-devkit/build-optimizer/webpack/simple-app" }}
          paths:
            - "tests/@angular-devkit/build-optimizer/webpack/simple-app/node_modules"
      - save_cache:
          key: angular_devkit-integration-aio{{ .Branch }}-{{ checksum "tests/@angular-devkit/build-optimizer/webpack/aio-app" }}
          paths:
            - "tests/@angular-devkit/build-optimizer/webpack/aio-app/node_modules"

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: bazel run @io_bazel_rules_typescript_node//:bin/npm install
      - run: bazel build ...

      - save_cache:
          key: angular_devkit-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"


workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - build
      - test
      - integration
